### ISSUE TITLE
gdb won't compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by goldug** [korcankaraokcu/PINCE#90]
Hey there.
I get a weird error that I can't seem to find the answer for.
When doing sh install_gdb.sh it goes pretty far until it fails like this:
`/usr/bin/ld: init.o: in function `initialize_all_files()':
/home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:182: undefined reference to `_initialize_ser_hard()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:203: undefined reference to `_initialize_tui_()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:221: undefined reference to `_initialize_break_catch_thro()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:231: undefined reference to `_initialize_corelo()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:241: undefined reference to `_initialize_d()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:243: undefined reference to `_initialize_d()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:245: undefined reference to `_initialize_d()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:246: undefined reference to `_initialize_d()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:247: undefined reference to `_initialize_d()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:257: undefined reference to `_initialize_frame_un()'
/usr/bin/ld: /home/goldug/git/PINCE/libPINCE/gdb_pince/gdb-10.1/gdb/init.c:268: undefined reference to `_initialize_inflo()'
collect2: error: ld returned 1 exit status
`

I'm guessing it's because ubuntu has updated something, but I have no idea what.

I mean, I can install PINCE by commenting out the running of install_gdb.sh in install_pince.sh and run pince with the gdb from ubuntu repository, but I don't know if that is incompatible or not. It seems to work, but I haven't tried everything yet.

**Comment by korcankaraokcu** [comment]
I can't seem to reproduce this issue with a clean install. Also, you can indeed set a new gdb path from the settings and use the system gdb. Looks like it's something related to gdb internals.

>I don't know if that is incompatible or not

It's compatible most of the time, as long as system gdb supports python3 and is up to date enough.

**Comment by goldug** [comment]
Just a quick update on the issue, I've tried it on a completely different laptop and gets the exact same error, except it's gdb-8.3.1.
Xubuntu 20.04.

**Comment by korcankaraokcu** [comment]
PINCE now uses system gdb instead of compiling its own. This issue is no more relevant
